### ISSUE TITLE
Website is down and no 'Issues" section for flyspray/flyspray repository

### ISSUE THREAD

**Issue by Neustradamus** [flyspray/flyspray-testing#1]
Dear @flyspray team, @peterdd, @jordanmendler,

The website is down...
- https://www.flyspray.org/
- https://bugs.flyspray.org/

In more, can you open the "Issues" section in the flyspray/flyspray GitHub repository?

Thanks in advance.

**Comment by Neustradamus** [comment]
@peterdd: Thanks!

You can transfer this issue in flyspray repository and after the next, please keep the order ;)

**Comment by Neustradamus** [comment]
@flyspray Team, @peterdd, @jordanmendler,

Can you transfer this issue in flyspray repository and after the next ones?
You have at right, a button to do it.
Important: Please respect order to have 1->1 / 2->2 / 3->3

I can not wait the original bugs.flyspray.org to recover my tickets (to have specific details)...

**Comment by Neustradamus** [comment]
@peterdd: You have not the button at right to transfer directly issues?
- https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by peterdd** [comment]
Done.

**Comment by Neustradamus** [comment]
@peterdd: Thanks!

You can do same for this ^^

And for your 799/800/801, you can delete completely with "Delete issue" button :)
